apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctv
  template:
    metadata:
      labels:
        app: ctv
    spec:
      containers:
      - image: okteto.dev/myu:latest
        name: ctv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0e979792-836c-4d4d-b4c7-2ac8ada3ef52"
        - name: Vless_Path
          value: "/vless123321"
        - name: Vmess_UUID
          value: "0e979792-836c-4d4d-b4c7-2ac8ada3ef52"
        - name: Vmess_Path
          value: "/vmess123321"
        - name: Share_Path
          value: "/binandgoogle"
